[github]
token = "ghp_жаңа_токен_осында"
owner = "aidarpavl"
repo = "Zhd_-Stolovaya-zaiavka"
branch = "main"
menu_path = "menu.csv"
daily_report_path = "Stolovaia ZHD1.csv"
monthly_report_path = "Stol_Zhd month1.csv"

[auth]
chef_password = "povar2026"